name: debian-spack-develop

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build zlip with spack-v0.16.3 in Debian container
      run: make v0.16.3
