name: debian-spack-develop-fixed

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build zlip with spack develop branch in Debian container and install py-distutils and libpython-dev
      run: make develop-fixed
